#!/bin/bash
# DataPilot Installation Script (GHCR Version)
# Fully automatic: asks only what it must, generates everything else.

set -e

echo "================================================="
echo "   DataPilot Installer"
echo "================================================="

# ─── 1. Docker check ──────────────────────────────────
if ! command -v docker &> /dev/null; then
    echo "Error: Docker is not installed."
    echo "See: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "Error: Docker Compose plugin is not installed."
    exit 1
fi

echo "Docker OK: $(docker --version)"

# ─── 2. Interactive questions (only what cannot be auto-generated) ──
echo ""
echo "--- Configuration ---"

read -p "Host IP or domain (browsers will use this to reach DataPilot) [localhost]: " host_ip
host_ip=${host_ip:-localhost}

read -p "Frontend port  [80]: " frontend_port
frontend_port=${frontend_port:-80}

read -p "Backend API port  [8008]: " backend_port
backend_port=${backend_port:-8008}

read -p "Database port (host-side)  [5432]: " db_port
db_port=${db_port:-5432}

read -p "Redis port (host-side)  [6379]: " redis_port
redis_port=${redis_port:-6379}

read -p "Database password [auto-generate]: " db_pass
if [ -z "$db_pass" ]; then
    db_pass="dp_$(head -c 16 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 20)"
    echo "  Generated DB password: $db_pass"
fi

echo ""
echo "--- GitHub Container Registry ---"
echo "You need a Personal Access Token (PAT) with read:packages scope."
read -p "GitHub Username: " gh_user
read -s -p "GitHub PAT: " gh_token
echo ""

if [ -z "$gh_user" ] || [ -z "$gh_token" ]; then
    echo "Error: GitHub username and token are required."
    exit 1
fi

# ─── 3. Auto-generate secrets ─────────────────────────
if command -v openssl &> /dev/null; then
    secret_key=$(openssl rand -hex 32)
    encryption_key=$(openssl rand -base64 32 | tr '+/' '-_')
    jwt_secret=$(openssl rand -hex 32)
else
    secret_key=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)
    encryption_key=$(head -c 32 /dev/urandom | base64 | tr '+/' '-_')
    jwt_secret=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)
fi

echo "Secrets generated automatically."

# ─── 4. Generate .env ─────────────────────────────────
cat << EOF > .env
# DataPilot Environment (auto-generated by install.sh)
HOST_IP=${host_ip}
FRONTEND_PORT=${frontend_port}
BACKEND_PORT=${backend_port}
DB_PORT=${db_port}
REDIS_PORT=${redis_port}

POSTGRES_USER=data_pilot_user
POSTGRES_PASSWORD=${db_pass}
POSTGRES_DB=data_pilot

SECRET_KEY=${secret_key}
ENCRYPTION_KEY=${encryption_key}
JWT_SECRET_KEY=${jwt_secret}

GHCR_FRONTEND_IMAGE=ghcr.io/datapilot-co/datapilot-frontend:latest
GHCR_BACKEND_IMAGE=ghcr.io/datapilot-co/datapilot-backend:release-ready
EOF

echo ".env created."

# ─── 5. Generate docker-compose.yml ───────────────────
cat << 'COMPOSE' > docker-compose.yml
services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-data_pilot_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_123}
      POSTGRES_DB: ${POSTGRES_DB:-data_pilot}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - data_pilot_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-data_pilot_user}", "-d", "${POSTGRES_DB:-data_pilot}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - data_pilot_redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    image: ${GHCR_BACKEND_IMAGE:-ghcr.io/datapilot-co/datapilot-backend:release-ready}
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-data_pilot_user}:${POSTGRES_PASSWORD:-secure_password_123}@db:5432/${POSTGRES_DB:-data_pilot}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=http://localhost:${FRONTEND_PORT:-80},http://${HOST_IP:-localhost}:${FRONTEND_PORT:-80}
      - PORT=8008
    ports:
      - "${BACKEND_PORT:-8008}:8008"

  frontend:
    image: ${GHCR_FRONTEND_IMAGE:-ghcr.io/datapilot-co/datapilot-frontend:latest}
    restart: always
    environment:
      - VITE_API_URL=http://${HOST_IP:-localhost}:${BACKEND_PORT:-8008}/api/v1
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend

volumes:
  data_pilot_postgres_data:
  data_pilot_redis_data:
COMPOSE

echo "docker-compose.yml created."

# ─── 6. GHCR login ────────────────────────────────────
echo ""
echo "Logging in to ghcr.io..."
echo "$gh_token" | docker login ghcr.io -u "$gh_user" --password-stdin

if [ $? -ne 0 ]; then
    echo "Error: GHCR authentication failed. Check your token."
    exit 1
fi

echo "GHCR login OK."

# ─── 7. Pull images ───────────────────────────────────
echo ""
echo "Pulling images..."
docker compose pull

# ─── 8. Start services (ordered) ──────────────────────
echo ""
echo "Starting services..."
docker compose up -d db redis

wait_for_healthy() {
    local svc="$1" max="${2:-90}" i=0
    echo "Waiting for ${svc}..."
    while [ "$i" -lt "$max" ]; do
        cid="$(docker compose ps -q "$svc")"
        if [ -n "$cid" ]; then
            h="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$cid" 2>/dev/null || true)"
            if [ "$h" = "healthy" ]; then
                echo "  ${svc}: healthy"
                return 0
            fi
        fi
        sleep 2
        i=$((i + 1))
    done
    echo "Error: ${svc} did not become healthy."
    return 1
}

wait_for_healthy "db" 120
wait_for_healthy "redis" 60

docker compose up -d backend
docker compose up -d frontend

# ─── 9. Wait for backend migration/seed completion ────
echo ""
echo "Waiting for backend migrations and seed..."
max_wait=240
i=0
while [ "$i" -lt "$max_wait" ]; do
    logs="$(docker compose logs --no-color backend 2>/dev/null || true)"
    if echo "$logs" | grep -q "Startup migrations complete." && \
       echo "$logs" | grep -q "Verified: Admin user exists"; then
        echo "  Backend migrations/seed: OK"
        break
    fi
    sleep 2
    i=$((i + 1))
done

if [ "$i" -ge "$max_wait" ]; then
    echo "Warning: Backend migration/seed did not complete in time."
    echo "Check logs: docker compose logs backend"
    exit 1
fi

# ─── 10. Verify admin user in DB ──────────────────────
echo "Verifying admin user in database..."
docker compose exec -T backend python - << 'PY'
from sqlalchemy import create_engine, text
import os
engine = create_engine(os.environ["DATABASE_URL"])
with engine.connect() as conn:
    row = conn.execute(text("SELECT email, role FROM users WHERE email = 'admin@datapilot.co' LIMIT 1")).fetchone()
    if not row:
        raise SystemExit("FAIL: Admin user not found.")
print("  Admin user verified.")
PY

# ─── 11. Done ─────────────────────────────────────────
front_url="http://${host_ip}"
if [ "$frontend_port" != "80" ]; then
    front_url="http://${host_ip}:${frontend_port}"
fi
api_url="http://${host_ip}:${backend_port}/docs"

echo ""
echo "================================================="
echo "  DataPilot installed successfully!"
echo ""
echo "  Frontend : ${front_url}"
echo "  API Docs : ${api_url}"
echo ""
echo "  Login:"
echo "    Email    : admin@datapilot.co"
echo "    Password : admin123"
echo ""
echo "  Change the default password after first login."
echo "================================================="
